version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # ERRO 4: Faltava dependência entre app e mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    # ERRO 5: Porta do MongoDB não estava exposta
    ports:
      - "27017:27017"
    # ERRO 6: MongoDB sem volume persistente
    volumes:
      - mongo-data:/data/db

# ERRO 7: Volume nomeado não estava definido
volumes:
  mongo-data:
